config/routes.rb
Rails.application.routes.draw do
  root to: 'recipes#index'

  resources :recipes

  get 'recipes/user_recipes/:id', to: 'recipes#user_recipes', as: :user_recipes

  get 'recipes/:id/edit_instructions', to: 'recipes#edit_instructions', as: :edit_instructions
  get 'recipes/:id/edit_ingredients', to: 'recipes#edit_ingredients', as: :edit_ingredients

  get 'users/signup', to: 'users#new'
  resources :users, except: :new

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  MIN_NAME_LENGTH = 2
  MAX_NAME_LENGTH = 100

  belongs_to :recipe, optional: true

  validates :name, presence: true, length: { minimum: MIN_NAME_LENGTH, maximum: MAX_NAME_LENGTH }
end

app/models/instruction.rb
class Instruction < ApplicationRecord
  MIN_STEP_LENGTH = 2
  MAX_STEP_LENGTH = 1000

  belongs_to :recipe, optional: true

  validates :step, presence: true, length: { minimum: MIN_STEP_LENGTH, maximum: MAX_STEP_LENGTH }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  MAX_TITLE_LENGTH = 100
  MIN_DESCRIPTION_LENGTH = 5
  MAX_DESCRIPTION_LENGTH = 1000

  has_many :instructions, dependent: :destroy, inverse_of: :recipe
  has_many :ingredients, dependent: :destroy, inverse_of: :recipe
  belongs_to :user, optional: true

  accepts_nested_attributes_for :instructions, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :ingredients, allow_destroy: true, reject_if: :all_blank

  validates :title, presence: true, length: { maximum: MAX_TITLE_LENGTH }
  validates :description, presence: true, length: { minimum: MIN_DESCRIPTION_LENGTH, maximum: MAX_DESCRIPTION_LENGTH }
end

app/models/user.rb
class User < ApplicationRecord
  MAX_USERNAME_LENGTH = 30
  MAX_EMAIL_LENGTH = 50
  MIN_PASSWORD_LENGTH = 6
  MIN_FIRST_NAME_LENGTH = 2
  MAX_FIRST_NAME_LENGTH = 100
  MIN_LAST_NAME_LENGTH = 2
  MAX_LAST_NAME_LENGTH = 100
  VALID_USERNAME_REGEX = /\A[a-zA-Z0-9]+([._]?[a-zA-Z0-9]+)*\z/
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  has_secure_password

  has_many :recipes, dependent: :destroy

  before_save :email_to_downcase

  validates :username, presence: true, length: { maximum: MAX_USERNAME_LENGTH },
  format: { with: VALID_USERNAME_REGEX },
  uniqueness: true
  validates :email, presence: true, length: { maximum: MAX_EMAIL_LENGTH },
  format: { with: VALID_EMAIL_REGEX },
  uniqueness: true
  validates :password, presence: true, length: { minimum: MIN_PASSWORD_LENGTH }
  validates :first_name, presence: true, length: { minimum: MIN_FIRST_NAME_LENGTH, maximum: MAX_FIRST_NAME_LENGTH }
  validates :last_name, presence: true, length: { minimum: MIN_LAST_NAME_LENGTH, maximum: MAX_LAST_NAME_LENGTH }

  private

  def email_to_downcase
    self.email = email.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  before_action :require_login

  private

  def require_login
    unless logged_in?
      flash[:danger] = 'Please Sign in to continue.'
      redirect_to login_path
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  skip_before_action :require_login, only: [:index]
  before_action :find_recipe, only: [:show, :edit, :edit_instructions, :edit_ingredients, :update, :destroy]
  before_action :set_user, only: [:edit, :edit_instructions, :edit_ingredients, :update, :destroy]

  def index
    @recipes = Recipe.all.order('created_at DESC')
  end

  def user_recipes
    @recipes = Recipe.all
    @user = User.find(params[:id])
  end

  def show
  end

  def new
    @recipe = Recipe.new
    6.times { @recipe.instructions.build }
    8.times { @recipe.ingredients.build }
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)

    if @recipe.save
      redirect_to @recipe
    else
      render :new
    end
  end

  def edit
    @recipe.instructions.build
    @recipe.ingredients.build
  end

  def edit_instructions
    3.times { @recipe.instructions.build }
  end

  def edit_ingredients
    3.times { @recipe.ingredients.build }
  end

  def update
    if @recipe.update(recipe_params)
      flash[:success] = "Recipe updated"
      redirect_to @recipe
    else
      render :edit
    end
  end

  def destroy
    @recipe.destroy
    redirect_to recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :description,
                                   instructions_attributes: [:id, :step, :_destroy],
                                   ingredients_attributes: [:id, :name, :_destroy])
  end

  def find_recipe
    @recipe = Recipe.find(params[:id])
  end

  def set_user
    unless equal_with_current_user?(@recipe.user)
      flash[:danger] = 'Wrong User'
      redirect_to(root_path)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user&.authenticate(params[:session][:password])
      log_in(user)
      flash[:success] = "Welcome #{user.first_name}!"
      redirect_to user
    else
      flash.now[:danger] = 'Sign in failed. Please try again.'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    @current_user = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create, :show]

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in(@user)
      redirect_to @user
    else
      render :new
    end
  end

  def edit; end

  def update
    if current_user.update(user_params)
      flash[:success] = "User updated"
      redirect_to current_user
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :first_name, :last_name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    current_user.present?
  end

  def equal_with_current_user?(other_user)
    current_user == other_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ingredients/_ingredient_fields.html.erb
<div class="nested-fields">
  <ul>
    <%= form.text_field :name, class: 'input is-medium', placeholder: 'Insert ingredient' %>
    <%= form.check_box :_destroy %>
    <%= form.label :_destroy, "Remove" %>
  </ul>
</div>

app/views/ingredients/_list_ingredients.html.erb
<ul>
  <% recipe.ingredients.each do |ingredient| %>
    <li><%= "#{ingredient.name}" %></li>
  <% end %>
</ul>

app/views/instructions/_instruction_fields.html.erb
<div class="nested-fields">
  <ul>
    <%= form.text_area :step, class: 'input is-medium', placeholder: 'Insert instruction' %>
    <%= form.check_box :_destroy %>
    <%= form.label :_destroy, "Remove" %>
  </ul>
</div>

app/views/instructions/_set_instructions.html.erb
<ul>
  <% count = 0 %>
  <% recipe.instructions.each do |instruction| %>
    <% count += 1 %>
    <%= "#{count}. " "#{instruction.step}" %>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeliciousRecipes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class="section">
      <div class="container">
        <%= render 'shared/nav_bar' %>
        <%= render 'shared/flash' %>
        <br>
        <h2 class="subtitle">
          <%= yield %>
        </h2>
      </div>
    </section>
  </body>
</html>

app/views/recipes/_form.html.erb
<div class="container">
  <div class="miltiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-4">
        <h1 class="title has-text-centered has-text-weight-bold is-italic"><%= title %></h1>
      </div>
    </div>

    <%= render 'shared/errors', object: @recipe %>

    <div class="column is-6 is-offset-3">
      <%= form_with model: @recipe, local: true do |form| %>
        <% unless local_assigns[:edit_ingredients] %>
          <% unless local_assigns[:edit_instructions] %>
            <div class="control">
              <p>
                <%= form.label :recipe_name, class: 'label is-medium' %>
                <%= form.text_field :title, class: 'input is-medium', placeholder: 'Recipe name' %>
              </p>
              <br>
            </div>
            <div class="control">
              <p>
                <%= form.label :description, class: 'label is-medium' %>
                <%= form.text_area :description, class: 'textarea is-medium', placeholder: 'Short description' %>
              </p>
              <br>
            </div>
          <% end %>
          <div class="control">
            <p>
              <%= form.label :instructions, class: 'label is-medium' %>
              <%= form.fields_for :instructions do |instructions_form| %>
                <%= render "instructions/instruction_fields", form: instructions_form %>
              <% end %>
            </p>
            <br>
          </div>
        <% end %>
        <% unless local_assigns[:edit_instructions] %>
          <div class="control">
            <p>
              <%= form.label :ingredients, class: 'label is-medium' %>
              <%= form.fields_for :ingredients do |ingredients_form| %>
                <%= render "ingredients/ingredient_fields", form: ingredients_form %>
              <% end %>
            </p>
            <br>
          </div>
        <% end %>
        <div class="control">
          <p>
            <%= form.submit submit, class: 'button is-success' %>
            <%= link_to 'Cancel', @recipe, class: 'button is-light' %>
          </p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/_recipe.html.erb
<div class="card block">
  <header class="card-header">
    <% if local_assigns[:index_user] %>
      <p class="title">
        <% if logged_in? %>
          <%= link_to recipe_path(recipe) do %>
            <span class="is-size-4 has-text-weight-bold"><%= recipe.title %></span>
          <% end %>
        <% else %>
          <span class="is-size-4 has-text-weight-bold"><%= recipe.title %></span>
        <% end %>
      </p>
    <% end %>
  </header>
  <div class="card-content">
    <div class="content">
      <%= recipe.description %>
    </div>
    <% if logged_in? && !local_assigns[:index_user] %>
      <div class="content">
        <p class="is-size-4 has-text-weight-bold">Instructions:</p>
        <%= render 'instructions/set_instructions', recipe: recipe %>
        <% if equal_with_current_user?(recipe.user) %>
          <%= link_to edit_instructions_path(recipe), class: 'card-footer-item has-text-weight-bold is-italic' do %>
            <span>Edit Instructions</span>
          <% end %>
        <% end %>
      </div>
      <div class="box is-half">
        <article class="media">
          <div class="media-left">
            <p class="is-size-4 has-text-weight-bold">Ingredients:</p>
            <%= render 'ingredients/list_ingredients', recipe: recipe %>
            <% if equal_with_current_user?(recipe.user) %>
              <%= link_to edit_ingredients_path(recipe), class: 'card-footer-item has-text-weight-bold is-italic' do %>
                <span>Edit Ingredients</span>
              <% end %>
            <% end %>
          </div>
        </article>
      </div>
    <% end %>
  </div>
  <nav class="level">
    <div class="level-left">
      <span class="is-size-7 is-italic"> &nbsp;Created:
        <%= recipe.created_at.localtime.strftime("%B %d, %Y") %>
      </span>
    </div>
    <% unless equal_with_current_user?(recipe.user) %>
    <div class="level">
      <strong>
        <span class="is-size-6 is-italic"> &nbsp;Created by:
          <%= link_to "#{recipe.user.first_name} #{recipe.user.last_name}", recipe.user %>
        </span>
      </strong>
    </div>
    <% end %>
    <div class="level-right">
      <span class="is-size-7 is-italic">Edited:
        <%= recipe.updated_at.localtime.strftime("%B %d, %Y") %> &nbsp;
      </span>
    </div>
  </nav>
  <footer class="card-footer">
    <% if logged_in? && equal_with_current_user?(recipe.user) %>
      <% unless local_assigns[:index_user] %>
          <%= link_to root_path, class: 'card-footer-item has-text-weight-bold' do %>
            <span>Home</span>
          <% end %>
      <% else %>
        <%= link_to recipe_path(recipe), class: 'card-footer-item has-text-weight-bold' do %>
          <span>Show</span>
        <% end %>
      <% end %>

      <%= link_to edit_recipe_path(recipe), class: 'card-footer-item has-text-weight-bold' do %>
        <span>Edit</span>
      <% end %>

      <%= link_to recipe_path(recipe), class: 'card-footer-item has-text-weight-bold',
        method: :delete, data: { confirm: 'Are you sure you want to delete this recipe?' } do %>
        <span>Delete</span>
      <% end %>
    <% elsif logged_in? %>
      <% unless local_assigns[:index_user] %>
        <%= link_to root_path, class: 'card-footer-item has-text-weight-bold' do %>
          <span>Home</span>
        <% end %>
      <% else %>
        <%= link_to recipe_path(recipe), class: 'card-footer-item has-text-weight-bold' do %>
          <span>Show</span>
        <% end %>
      <% end %>
    <% end %>
  </footer>
</div>

app/views/recipes/edit.html.erb
<%= render 'form',
recipe: @recipe,
title: "Edit",
submit: 'Update Recipe' %>

app/views/recipes/edit_ingredients.html.erb
<%= render 'form',
recipe: @recipe,
title: "Edit ingredients",
submit: 'Update',
edit_ingredients: true %>

app/views/recipes/edit_instructions.html.erb
<%= render 'form',
recipe: @recipe,
title: "Edit instructions",
submit: 'Update',
edit_instructions: true %>

app/views/recipes/index.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-4">
        <h1 class="title has-text-centered has-text-weight-bold is-italic"> Recipes </h1>
      </div>

      <%= render @recipes, index_user: true %>

    </div>
  </div>
</div>

app/views/recipes/new.html.erb
<%= render 'form',
recipe: @recipe,
title: 'Add new Recipe',
submit: 'Create Recipe' %>

app/views/recipes/show.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-8 is-offset-2">
      <div class="content is-size-4">
        <h1 class="title has-text-centered has-text-weight-bold is-italic"> <%= @recipe.title %> </h1>
      </div>

      <%= render @recipe %>

    </div>
  </div>
</div>

app/views/recipes/user_recipes.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-8 is-offset-2">
      <div class="content is-size-4">
        <h1 class="title has-text-centered has-text-weight-bold is-italic"><%= "#{ @user.first_name }" %>'s Recipes </h1>
      </div>

      <% @recipes.each do |recipe| %>
        <% if recipe.user == @user %>
          <%= render recipe %>
        <% end %>
      <% end %>

    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
    <% if object.errors.any? %>
      <div class="column is-6 is-offset-3">
        <article class="message is-danger">
          <div class="message-body">
            <p><strong><%= pluralize(object.errors.count, "error") %> prohibited from being saved:</strong></p>
            <br>
            <p>
            <% object.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </p>
          </div>
        </article>
      </div>
    <% end %>

app/views/shared/_flash.html.erb
<div class="container">
  <div class="columns is-multiline">
    <% flash.each do |name, msg| -%>

    <div class="column is-10 is-offset-1">
      <div class="notification has-text-centered is-<%= name %>">
        <%= msg %>
      </div>
    </div>

    <% end -%>
  </div>
</div>

app/views/shared/_nav_bar.html.erb
<nav class="navbar is-spaced is-fixed-top" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <strong><%= link_to 'Delicious Recipes', root_path, class: 'navbar-item is-size-2 is-italic' %></strong>
    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navBar">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div id="navBar" class="navbar-menu">
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if logged_in? %>
            <%= link_to 'Add Recipe', new_recipe_path, class: 'button is-primary has-text-weight-bold' %>
            <%= link_to 'My Recipes', user_recipes_path(current_user), class: 'button is-info has-text-weight-bold' %>
            &nbsp &nbsp
            <% if logged_in? %>
              <%= link_to 'Edit User', edit_user_path(current_user), class: 'button is-light has-text-weight-bold' %>
            <% end %>

            <%= link_to 'My Profile', user_path(current_user), class: 'button is-light has-text-weight-bold' %>
            <%= link_to 'Sign out', logout_path, method: :delete, class: 'button is-danger has-text-weight-bold' %>
          <% else %>
            <%= link_to 'Sign in', login_path, class: 'button is-primary has-text-weight-bold' %>
            <%= link_to 'Sign up', users_signup_path, class: 'button is-primary has-text-weight-bold' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/users/_form.html.erb
<div class="container">
  <div class="miltiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-4">
        <h1 class="title has-text-centered has-text-weight-bold is-italic">New User</h1>
      </div>
    </div>

    <%= render 'shared/errors', object: user %>

    <div class="column is-4 is-offset-4">
      <%= form_with model: user, local: true do |form| %>
        <div class="field">
          <%= form.label :username, class: 'label' %>
          <div class="control">
            <%= form.text_field :username, class: 'input', placeholder: 'Insert username' %>
          </div>
        </div>

        <div class="field">
          <%= form.label :email, class: 'label' %>
          <div class="control">
            <%= form.text_field :email, class: 'input', placeholder: 'Insert your email' %>
          </div>
        </div>

        <div class="field">
          <%= form.label :first_name, class: 'label' %>
          <div class="control">
            <%= form.text_field :first_name, class: 'input', placeholder: 'Insert your first name' %>
          </div>
        </div>

        <div class="field">
          <%= form.label :last_name, class: 'label' %>
          <div class="control">
            <%= form.text_field :last_name, class: 'input', placeholder: 'Insert your last name' %>
          </div>
        </div>

        <div class="field">
          <%= form.label :password, class: 'label' %>
          <p class="control">
            <%= form.text_field :password, class: 'input', type: 'password', placeholder: 'Insert password' %>
          </p>
        </div>

        <div class="field">
          <%= form.label :password_confirmation, class: 'label' %>
          <p class="control">
            <%= form.text_field :password_confirmation, class: 'input', type: 'password', placeholder: 'Confirm password' %>
          </p>
        </div>

        <div class="field">
          <p class="control">
            <%= form.submit submit, class: 'button is-success' %>
            <%= link_to 'Cancel', cancel, class: 'button is-danger' %>
          </p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<%= render 'form',
user: current_user,
title: "Edit User",
submit: 'Update User',
cancel: user_path(current_user) %>

app/views/users/new.html.erb
<%= render 'form',
user: @user,
title: "New User",
submit: 'Create User',
cancel: root_path %>

app/views/users/show.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="user column is-6 is-offset-3 has-text-centered">
      <ul class="has-text-weight-bold is-italic">
        <li class="title">
          Full name: <%= "#{@user.first_name} #{@user.last_name}" %>
        </li>
        <li class="title">
          Username: <%= "#{@user.username}" %>
        </li>
        <li class="title">
          e-mail: <%= "#{@user.email}" %>
        </li>
      </ul>
      <br>
      <div class="title">
        <%= link_to 'Home', root_path, class: 'button is-light has-text-weight-bold' %>
      </div>
    </div>
    <div class="user_recipes column is-6 is-offset-3 has-text-centered">
      <% if @user.recipes.count != 0 %>
        <div class="title">
          <% if equal_with_current_user?(@user) %>
            You have
          <% else %>
            <%= "#{@user.first_name} " %>have
          <% end %>
          <i><%= pluralize(@user.recipes.count, "Recipe") %></i>
        </div>
        <div class="has-text-weight-bold is-italic">
          <% count = 0 %>
            <% @user.recipes.each do |recipe| %>
            <% if recipe.user == @user %>
              <ul>
                <% count += 1 %>
                <li><%= link_to "#{count}. #{recipe.title}", recipe_path(recipe) %></li>
              </ul>
            <% end %>
          <% end %>
        </div>
      <% else %>
        <div class="title">
                  <% if equal_with_current_user?(@user) %>
            You don't have <i>Recipes</i> yet.
          <% else %>
            <%= "#{@user.first_name} " %>don't have <i>Recipes</i>.
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>